export const Routes = {
  Intro: 'Intro',
  Home: 'Home',
  Search: 'SearchScreen',
  Profile: 'Profile',
  Library: 'VideoLibraryFeed',
  Login: 'Login',
  NovideoLink: 'NovideoLink',
  Register: 'Register',
  ForgetPass: 'ForgetPass',
  CheckMail: 'CheckMail',
  ResetPass: 'ResetPass',
  ProfileEdit: 'ProfileEdit',
  VideoDetail: 'VideoDetail',
};
